
#ifndef TEMP_POINTERS_MP
#define TEMP_POINTERS_MP
namespace Template
{
	namespace Modify
	{
		template<typename T, unsigned int N>
		struct addNPointers;
		template<typename T>
		struct addNPointers<T,1>;
		template<typename T>
		struct addNPointers<T,2>;
		template<typename T>
		struct addNPointers<T,3>;
		template<typename T>
		struct addNPointers<T,4>;
		template<typename T>
		struct addNPointers<T,5>;
		template<typename T>
		struct addNPointers<T,6>;
		template<typename T>
		struct addNPointers<T,7>;
		template<typename T>
		struct addNPointers<T,8>;
		template<typename T>
		struct addNPointers<T,9>;
		template<typename T>
		struct addNPointers<T,10>;
		template<typename T>
		struct addNPointers<T,11>;
		template<typename T>
		struct addNPointers<T,12>;
		template<typename T>
		struct addNPointers<T,13>;
		template<typename T>
		struct addNPointers<T,14>;
		template<typename T>
		struct addNPointers<T,15>;
		template<typename T>
		struct addNPointers<T,16>;
		template<typename T>
		struct addNPointers<T,17>;
		template<typename T>
		struct addNPointers<T,18>;
		template<typename T>
		struct addNPointers<T,19>;
		template<typename T>
		struct addNPointers<T,20>;
		template<typename T>
		struct addNPointers<T,21>;
		template<typename T>
		struct addNPointers<T,22>;
		template<typename T>
		struct addNPointers<T,23>;
		template<typename T>
		struct addNPointers<T,24>;
		template<typename T>
		struct addNPointers<T,25>;
		template<typename T>
		struct addNPointers<T,26>;
		template<typename T>
		struct addNPointers<T,27>;
		template<typename T>
		struct addNPointers<T,28>;
		template<typename T>
		struct addNPointers<T,29>;
		template<typename T>
		struct addNPointers<T,30>;
		template<typename T>
		struct addNPointers<T,31>;
		template<typename T>
		struct addNPointers<T,32>;
		template<typename T>
		struct addNPointers<T,33>;
		template<typename T>
		struct addNPointers<T,34>;
		template<typename T>
		struct addNPointers<T,35>;
		template<typename T>
		struct addNPointers<T,36>;
		template<typename T>
		struct addNPointers<T,37>;
		template<typename T>
		struct addNPointers<T,38>;
		template<typename T>
		struct addNPointers<T,39>;
		template<typename T>
		struct addNPointers<T,40>;
		template<typename T>
		struct addNPointers<T,41>;
		template<typename T>
		struct addNPointers<T,42>;
		template<typename T>
		struct addNPointers<T,43>;
		template<typename T>
		struct addNPointers<T,44>;
		template<typename T>
		struct addNPointers<T,45>;
		template<typename T>
		struct addNPointers<T,46>;
		template<typename T>
		struct addNPointers<T,47>;
		template<typename T>
		struct addNPointers<T,48>;
		template<typename T>
		struct addNPointers<T,49>;
		template<typename T>
		struct addNPointers<T,50>;
		template<typename T>
		struct addNPointers<T,51>;
		template<typename T>
		struct addNPointers<T,52>;
		template<typename T>
		struct addNPointers<T,53>;
		template<typename T>
		struct addNPointers<T,54>;
		template<typename T>
		struct addNPointers<T,55>;
		template<typename T>
		struct addNPointers<T,56>;
		template<typename T>
		struct addNPointers<T,57>;
		template<typename T>
		struct addNPointers<T,58>;
		template<typename T>
		struct addNPointers<T,59>;
		template<typename T>
		struct addNPointers<T,60>;
		template<typename T>
		struct addNPointers<T,61>;
		template<typename T>
		struct addNPointers<T,62>;
		template<typename T>
		struct addNPointers<T,63>;
		template<typename T>
		struct addNPointers<T,64>;
		template<typename T>
		struct addNPointers<T,65>;
		template<typename T>
		struct addNPointers<T,66>;
		template<typename T>
		struct addNPointers<T,67>;
		template<typename T>
		struct addNPointers<T,68>;
		template<typename T>
		struct addNPointers<T,69>;
		template<typename T>
		struct addNPointers<T,70>;
		template<typename T>
		struct addNPointers<T,71>;
		template<typename T>
		struct addNPointers<T,72>;
		template<typename T>
		struct addNPointers<T,73>;
		template<typename T>
		struct addNPointers<T,74>;
		template<typename T>
		struct addNPointers<T,75>;
		template<typename T>
		struct addNPointers<T,76>;
		template<typename T>
		struct addNPointers<T,77>;
		template<typename T>
		struct addNPointers<T,78>;
		template<typename T>
		struct addNPointers<T,79>;
		template<typename T>
		struct addNPointers<T,80>;
		template<typename T>
		struct addNPointers<T,81>;
		template<typename T>
		struct addNPointers<T,82>;
		template<typename T>
		struct addNPointers<T,83>;
		template<typename T>
		struct addNPointers<T,84>;
		template<typename T>
		struct addNPointers<T,85>;
		template<typename T>
		struct addNPointers<T,86>;
		template<typename T>
		struct addNPointers<T,87>;
		template<typename T>
		struct addNPointers<T,88>;
		template<typename T>
		struct addNPointers<T,89>;
		template<typename T>
		struct addNPointers<T,90>;
		template<typename T>
		struct addNPointers<T,91>;
		template<typename T>
		struct addNPointers<T,92>;
		template<typename T>
		struct addNPointers<T,93>;
		template<typename T>
		struct addNPointers<T,94>;
		template<typename T>
		struct addNPointers<T,95>;
		template<typename T>
		struct addNPointers<T,96>;
		template<typename T>
		struct addNPointers<T,97>;
		template<typename T>
		struct addNPointers<T,98>;
		template<typename T>
		struct addNPointers<T,99>;
		template<typename T>
		struct addNPointers<T,100>;
		template<typename T>
		struct addNPointers<T,101>;
		template<typename T>
		struct addNPointers<T,102>;
		template<typename T>
		struct addNPointers<T,103>;
		template<typename T>
		struct addNPointers<T,104>;
		template<typename T>
		struct addNPointers<T,105>;
		template<typename T>
		struct addNPointers<T,106>;
		template<typename T>
		struct addNPointers<T,107>;
		template<typename T>
		struct addNPointers<T,108>;
		template<typename T>
		struct addNPointers<T,109>;
		template<typename T>
		struct addNPointers<T,110>;
		template<typename T>
		struct addNPointers<T,111>;
		template<typename T>
		struct addNPointers<T,112>;
		template<typename T>
		struct addNPointers<T,113>;
		template<typename T>
		struct addNPointers<T,114>;
		template<typename T>
		struct addNPointers<T,115>;
		template<typename T>
		struct addNPointers<T,116>;
		template<typename T>
		struct addNPointers<T,117>;
		template<typename T>
		struct addNPointers<T,118>;
		template<typename T>
		struct addNPointers<T,119>;
		template<typename T>
		struct addNPointers<T,120>;
		template<typename T>
		struct addNPointers<T,121>;
		template<typename T>
		struct addNPointers<T,122>;
		template<typename T>
		struct addNPointers<T,123>;
		template<typename T>
		struct addNPointers<T,124>;
		template<typename T>
		struct addNPointers<T,125>;
		template<typename T>
		struct addNPointers<T,126>;
		template<typename T>
		struct addNPointers<T,127>;
		template<typename T>
		struct addNPointers<T,128>;
		template<typename T>
		struct addNPointers<T,129>;
		template<typename T>
		struct addNPointers<T,130>;
		template<typename T>
		struct addNPointers<T,131>;
		template<typename T>
		struct addNPointers<T,132>;
		template<typename T>
		struct addNPointers<T,133>;
		template<typename T>
		struct addNPointers<T,134>;
		template<typename T>
		struct addNPointers<T,135>;
		template<typename T>
		struct addNPointers<T,136>;
		template<typename T>
		struct addNPointers<T,137>;
		template<typename T>
		struct addNPointers<T,138>;
		template<typename T>
		struct addNPointers<T,139>;
		template<typename T>
		struct addNPointers<T,140>;
		template<typename T>
		struct addNPointers<T,141>;
		template<typename T>
		struct addNPointers<T,142>;
		template<typename T>
		struct addNPointers<T,143>;
		template<typename T>
		struct addNPointers<T,144>;
		template<typename T>
		struct addNPointers<T,145>;
		template<typename T>
		struct addNPointers<T,146>;
		template<typename T>
		struct addNPointers<T,147>;
		template<typename T>
		struct addNPointers<T,148>;
		template<typename T>
		struct addNPointers<T,149>;
		template<typename T>
		struct addNPointers<T,150>;
		template<typename T>
		struct addNPointers<T,151>;
		template<typename T>
		struct addNPointers<T,152>;
		template<typename T>
		struct addNPointers<T,153>;
		template<typename T>
		struct addNPointers<T,154>;
		template<typename T>
		struct addNPointers<T,155>;
		template<typename T>
		struct addNPointers<T,156>;
		template<typename T>
		struct addNPointers<T,157>;
		template<typename T>
		struct addNPointers<T,158>;
		template<typename T>
		struct addNPointers<T,159>;
		template<typename T>
		struct addNPointers<T,160>;
		template<typename T>
		struct addNPointers<T,161>;
		template<typename T>
		struct addNPointers<T,162>;
		template<typename T>
		struct addNPointers<T,163>;
		template<typename T>
		struct addNPointers<T,164>;
		template<typename T>
		struct addNPointers<T,165>;
		template<typename T>
		struct addNPointers<T,166>;
		template<typename T>
		struct addNPointers<T,167>;
		template<typename T>
		struct addNPointers<T,168>;
		template<typename T>
		struct addNPointers<T,169>;
		template<typename T>
		struct addNPointers<T,170>;
		template<typename T>
		struct addNPointers<T,171>;
		template<typename T>
		struct addNPointers<T,172>;
		template<typename T>
		struct addNPointers<T,173>;
		template<typename T>
		struct addNPointers<T,174>;
		template<typename T>
		struct addNPointers<T,175>;
		template<typename T>
		struct addNPointers<T,176>;
		template<typename T>
		struct addNPointers<T,177>;
		template<typename T>
		struct addNPointers<T,178>;
		template<typename T>
		struct addNPointers<T,179>;
		template<typename T>
		struct addNPointers<T,180>;
		template<typename T>
		struct addNPointers<T,181>;
		template<typename T>
		struct addNPointers<T,182>;
		template<typename T>
		struct addNPointers<T,183>;
		template<typename T>
		struct addNPointers<T,184>;
		template<typename T>
		struct addNPointers<T,185>;
		template<typename T>
		struct addNPointers<T,186>;
		template<typename T>
		struct addNPointers<T,187>;
		template<typename T>
		struct addNPointers<T,188>;
		template<typename T>
		struct addNPointers<T,189>;
		template<typename T>
		struct addNPointers<T,190>;
		template<typename T>
		struct addNPointers<T,191>;
		template<typename T>
		struct addNPointers<T,192>;
		template<typename T>
		struct addNPointers<T,193>;
		template<typename T>
		struct addNPointers<T,194>;
		template<typename T>
		struct addNPointers<T,195>;
		template<typename T>
		struct addNPointers<T,196>;
		template<typename T>
		struct addNPointers<T,197>;
		template<typename T>
		struct addNPointers<T,198>;
		template<typename T>
		struct addNPointers<T,199>;
		template<typename T>
		struct addNPointers<T,200>;
		template<typename T>
		struct addNPointers<T,201>;
		template<typename T>
		struct addNPointers<T,202>;
		template<typename T>
		struct addNPointers<T,203>;
		template<typename T>
		struct addNPointers<T,204>;
		template<typename T>
		struct addNPointers<T,205>;
		template<typename T>
		struct addNPointers<T,206>;
		template<typename T>
		struct addNPointers<T,207>;
		template<typename T>
		struct addNPointers<T,208>;
		template<typename T>
		struct addNPointers<T,209>;
		template<typename T>
		struct addNPointers<T,210>;
		template<typename T>
		struct addNPointers<T,211>;
		template<typename T>
		struct addNPointers<T,212>;
		template<typename T>
		struct addNPointers<T,213>;
		template<typename T>
		struct addNPointers<T,214>;
		template<typename T>
		struct addNPointers<T,215>;
		template<typename T>
		struct addNPointers<T,216>;
		template<typename T>
		struct addNPointers<T,217>;
		template<typename T>
		struct addNPointers<T,218>;
		template<typename T>
		struct addNPointers<T,219>;
		template<typename T>
		struct addNPointers<T,220>;
		template<typename T>
		struct addNPointers<T,221>;
		template<typename T>
		struct addNPointers<T,222>;
		template<typename T>
		struct addNPointers<T,223>;
		template<typename T>
		struct addNPointers<T,224>;
		template<typename T>
		struct addNPointers<T,225>;
		template<typename T>
		struct addNPointers<T,226>;
		template<typename T>
		struct addNPointers<T,227>;
		template<typename T>
		struct addNPointers<T,228>;
		template<typename T>
		struct addNPointers<T,229>;
		template<typename T>
		struct addNPointers<T,230>;
		template<typename T>
		struct addNPointers<T,231>;
		template<typename T>
		struct addNPointers<T,232>;
		template<typename T>
		struct addNPointers<T,233>;
		template<typename T>
		struct addNPointers<T,234>;
		template<typename T>
		struct addNPointers<T,235>;
		template<typename T>
		struct addNPointers<T,236>;
		template<typename T>
		struct addNPointers<T,237>;
		template<typename T>
		struct addNPointers<T,238>;
		template<typename T>
		struct addNPointers<T,239>;
		template<typename T>
		struct addNPointers<T,240>;
		template<typename T>
		struct addNPointers<T,241>;
		template<typename T>
		struct addNPointers<T,242>;
		template<typename T>
		struct addNPointers<T,243>;
		template<typename T>
		struct addNPointers<T,244>;
		template<typename T>
		struct addNPointers<T,245>;
		template<typename T>
		struct addNPointers<T,246>;
		template<typename T>
		struct addNPointers<T,247>;
		template<typename T>
		struct addNPointers<T,248>;
		template<typename T>
		struct addNPointers<T,249>;
		template<typename T>
		struct addNPointers<T,250>;
		template<typename T>
		struct addNPointers<T,251>;
		template<typename T>
		struct addNPointers<T,252>;
		template<typename T>
		struct addNPointers<T,253>;
		template<typename T>
		struct addNPointers<T,254>;
		template<typename T>
		struct addNPointers<T,255>;
		template<typename T>
		struct addNPointers<T,256>;
	};
}
#include "temp_pointers_mP.hpp"
#endif
