
#ifndef TEMP_POINTERS_MP
#define TEMP_POINTERS_MP
namespace Template
{
	namespace Modify
	{
		template<typename T, unsigned int N>
		struct makePointer;
		template<typename T>
		struct makePointer<T,1>;
		template<typename T>
		struct makePointer<T,2>;
		template<typename T>
		struct makePointer<T,3>;
		template<typename T>
		struct makePointer<T,4>;
		template<typename T>
		struct makePointer<T,5>;
		template<typename T>
		struct makePointer<T,6>;
		template<typename T>
		struct makePointer<T,7>;
		template<typename T>
		struct makePointer<T,8>;
		template<typename T>
		struct makePointer<T,9>;
		template<typename T>
		struct makePointer<T,10>;
		template<typename T>
		struct makePointer<T,11>;
		template<typename T>
		struct makePointer<T,12>;
		template<typename T>
		struct makePointer<T,13>;
		template<typename T>
		struct makePointer<T,14>;
		template<typename T>
		struct makePointer<T,15>;
		template<typename T>
		struct makePointer<T,16>;
		template<typename T>
		struct makePointer<T,17>;
		template<typename T>
		struct makePointer<T,18>;
		template<typename T>
		struct makePointer<T,19>;
		template<typename T>
		struct makePointer<T,20>;
		template<typename T>
		struct makePointer<T,21>;
		template<typename T>
		struct makePointer<T,22>;
		template<typename T>
		struct makePointer<T,23>;
		template<typename T>
		struct makePointer<T,24>;
		template<typename T>
		struct makePointer<T,25>;
		template<typename T>
		struct makePointer<T,26>;
		template<typename T>
		struct makePointer<T,27>;
		template<typename T>
		struct makePointer<T,28>;
		template<typename T>
		struct makePointer<T,29>;
		template<typename T>
		struct makePointer<T,30>;
		template<typename T>
		struct makePointer<T,31>;
		template<typename T>
		struct makePointer<T,32>;
		template<typename T>
		struct makePointer<T,33>;
		template<typename T>
		struct makePointer<T,34>;
		template<typename T>
		struct makePointer<T,35>;
		template<typename T>
		struct makePointer<T,36>;
		template<typename T>
		struct makePointer<T,37>;
		template<typename T>
		struct makePointer<T,38>;
		template<typename T>
		struct makePointer<T,39>;
		template<typename T>
		struct makePointer<T,40>;
		template<typename T>
		struct makePointer<T,41>;
		template<typename T>
		struct makePointer<T,42>;
		template<typename T>
		struct makePointer<T,43>;
		template<typename T>
		struct makePointer<T,44>;
		template<typename T>
		struct makePointer<T,45>;
		template<typename T>
		struct makePointer<T,46>;
		template<typename T>
		struct makePointer<T,47>;
		template<typename T>
		struct makePointer<T,48>;
		template<typename T>
		struct makePointer<T,49>;
		template<typename T>
		struct makePointer<T,50>;
		template<typename T>
		struct makePointer<T,51>;
		template<typename T>
		struct makePointer<T,52>;
		template<typename T>
		struct makePointer<T,53>;
		template<typename T>
		struct makePointer<T,54>;
		template<typename T>
		struct makePointer<T,55>;
		template<typename T>
		struct makePointer<T,56>;
		template<typename T>
		struct makePointer<T,57>;
		template<typename T>
		struct makePointer<T,58>;
		template<typename T>
		struct makePointer<T,59>;
		template<typename T>
		struct makePointer<T,60>;
		template<typename T>
		struct makePointer<T,61>;
		template<typename T>
		struct makePointer<T,62>;
		template<typename T>
		struct makePointer<T,63>;
		template<typename T>
		struct makePointer<T,64>;
		template<typename T>
		struct makePointer<T,65>;
		template<typename T>
		struct makePointer<T,66>;
		template<typename T>
		struct makePointer<T,67>;
		template<typename T>
		struct makePointer<T,68>;
		template<typename T>
		struct makePointer<T,69>;
		template<typename T>
		struct makePointer<T,70>;
		template<typename T>
		struct makePointer<T,71>;
		template<typename T>
		struct makePointer<T,72>;
		template<typename T>
		struct makePointer<T,73>;
		template<typename T>
		struct makePointer<T,74>;
		template<typename T>
		struct makePointer<T,75>;
		template<typename T>
		struct makePointer<T,76>;
		template<typename T>
		struct makePointer<T,77>;
		template<typename T>
		struct makePointer<T,78>;
		template<typename T>
		struct makePointer<T,79>;
		template<typename T>
		struct makePointer<T,80>;
		template<typename T>
		struct makePointer<T,81>;
		template<typename T>
		struct makePointer<T,82>;
		template<typename T>
		struct makePointer<T,83>;
		template<typename T>
		struct makePointer<T,84>;
		template<typename T>
		struct makePointer<T,85>;
		template<typename T>
		struct makePointer<T,86>;
		template<typename T>
		struct makePointer<T,87>;
		template<typename T>
		struct makePointer<T,88>;
		template<typename T>
		struct makePointer<T,89>;
		template<typename T>
		struct makePointer<T,90>;
		template<typename T>
		struct makePointer<T,91>;
		template<typename T>
		struct makePointer<T,92>;
		template<typename T>
		struct makePointer<T,93>;
		template<typename T>
		struct makePointer<T,94>;
		template<typename T>
		struct makePointer<T,95>;
		template<typename T>
		struct makePointer<T,96>;
		template<typename T>
		struct makePointer<T,97>;
		template<typename T>
		struct makePointer<T,98>;
		template<typename T>
		struct makePointer<T,99>;
		template<typename T>
		struct makePointer<T,100>;
		template<typename T>
		struct makePointer<T,101>;
		template<typename T>
		struct makePointer<T,102>;
		template<typename T>
		struct makePointer<T,103>;
		template<typename T>
		struct makePointer<T,104>;
		template<typename T>
		struct makePointer<T,105>;
		template<typename T>
		struct makePointer<T,106>;
		template<typename T>
		struct makePointer<T,107>;
		template<typename T>
		struct makePointer<T,108>;
		template<typename T>
		struct makePointer<T,109>;
		template<typename T>
		struct makePointer<T,110>;
		template<typename T>
		struct makePointer<T,111>;
		template<typename T>
		struct makePointer<T,112>;
		template<typename T>
		struct makePointer<T,113>;
		template<typename T>
		struct makePointer<T,114>;
		template<typename T>
		struct makePointer<T,115>;
		template<typename T>
		struct makePointer<T,116>;
		template<typename T>
		struct makePointer<T,117>;
		template<typename T>
		struct makePointer<T,118>;
		template<typename T>
		struct makePointer<T,119>;
		template<typename T>
		struct makePointer<T,120>;
		template<typename T>
		struct makePointer<T,121>;
		template<typename T>
		struct makePointer<T,122>;
		template<typename T>
		struct makePointer<T,123>;
		template<typename T>
		struct makePointer<T,124>;
		template<typename T>
		struct makePointer<T,125>;
		template<typename T>
		struct makePointer<T,126>;
		template<typename T>
		struct makePointer<T,127>;
		template<typename T>
		struct makePointer<T,128>;
		template<typename T>
		struct makePointer<T,129>;
		template<typename T>
		struct makePointer<T,130>;
		template<typename T>
		struct makePointer<T,131>;
		template<typename T>
		struct makePointer<T,132>;
		template<typename T>
		struct makePointer<T,133>;
		template<typename T>
		struct makePointer<T,134>;
		template<typename T>
		struct makePointer<T,135>;
		template<typename T>
		struct makePointer<T,136>;
		template<typename T>
		struct makePointer<T,137>;
		template<typename T>
		struct makePointer<T,138>;
		template<typename T>
		struct makePointer<T,139>;
		template<typename T>
		struct makePointer<T,140>;
		template<typename T>
		struct makePointer<T,141>;
		template<typename T>
		struct makePointer<T,142>;
		template<typename T>
		struct makePointer<T,143>;
		template<typename T>
		struct makePointer<T,144>;
		template<typename T>
		struct makePointer<T,145>;
		template<typename T>
		struct makePointer<T,146>;
		template<typename T>
		struct makePointer<T,147>;
		template<typename T>
		struct makePointer<T,148>;
		template<typename T>
		struct makePointer<T,149>;
		template<typename T>
		struct makePointer<T,150>;
		template<typename T>
		struct makePointer<T,151>;
		template<typename T>
		struct makePointer<T,152>;
		template<typename T>
		struct makePointer<T,153>;
		template<typename T>
		struct makePointer<T,154>;
		template<typename T>
		struct makePointer<T,155>;
		template<typename T>
		struct makePointer<T,156>;
		template<typename T>
		struct makePointer<T,157>;
		template<typename T>
		struct makePointer<T,158>;
		template<typename T>
		struct makePointer<T,159>;
		template<typename T>
		struct makePointer<T,160>;
		template<typename T>
		struct makePointer<T,161>;
		template<typename T>
		struct makePointer<T,162>;
		template<typename T>
		struct makePointer<T,163>;
		template<typename T>
		struct makePointer<T,164>;
		template<typename T>
		struct makePointer<T,165>;
		template<typename T>
		struct makePointer<T,166>;
		template<typename T>
		struct makePointer<T,167>;
		template<typename T>
		struct makePointer<T,168>;
		template<typename T>
		struct makePointer<T,169>;
		template<typename T>
		struct makePointer<T,170>;
		template<typename T>
		struct makePointer<T,171>;
		template<typename T>
		struct makePointer<T,172>;
		template<typename T>
		struct makePointer<T,173>;
		template<typename T>
		struct makePointer<T,174>;
		template<typename T>
		struct makePointer<T,175>;
		template<typename T>
		struct makePointer<T,176>;
		template<typename T>
		struct makePointer<T,177>;
		template<typename T>
		struct makePointer<T,178>;
		template<typename T>
		struct makePointer<T,179>;
		template<typename T>
		struct makePointer<T,180>;
		template<typename T>
		struct makePointer<T,181>;
		template<typename T>
		struct makePointer<T,182>;
		template<typename T>
		struct makePointer<T,183>;
		template<typename T>
		struct makePointer<T,184>;
		template<typename T>
		struct makePointer<T,185>;
		template<typename T>
		struct makePointer<T,186>;
		template<typename T>
		struct makePointer<T,187>;
		template<typename T>
		struct makePointer<T,188>;
		template<typename T>
		struct makePointer<T,189>;
		template<typename T>
		struct makePointer<T,190>;
		template<typename T>
		struct makePointer<T,191>;
		template<typename T>
		struct makePointer<T,192>;
		template<typename T>
		struct makePointer<T,193>;
		template<typename T>
		struct makePointer<T,194>;
		template<typename T>
		struct makePointer<T,195>;
		template<typename T>
		struct makePointer<T,196>;
		template<typename T>
		struct makePointer<T,197>;
		template<typename T>
		struct makePointer<T,198>;
		template<typename T>
		struct makePointer<T,199>;
		template<typename T>
		struct makePointer<T,200>;
		template<typename T>
		struct makePointer<T,201>;
		template<typename T>
		struct makePointer<T,202>;
		template<typename T>
		struct makePointer<T,203>;
		template<typename T>
		struct makePointer<T,204>;
		template<typename T>
		struct makePointer<T,205>;
		template<typename T>
		struct makePointer<T,206>;
		template<typename T>
		struct makePointer<T,207>;
		template<typename T>
		struct makePointer<T,208>;
		template<typename T>
		struct makePointer<T,209>;
		template<typename T>
		struct makePointer<T,210>;
		template<typename T>
		struct makePointer<T,211>;
		template<typename T>
		struct makePointer<T,212>;
		template<typename T>
		struct makePointer<T,213>;
		template<typename T>
		struct makePointer<T,214>;
		template<typename T>
		struct makePointer<T,215>;
		template<typename T>
		struct makePointer<T,216>;
		template<typename T>
		struct makePointer<T,217>;
		template<typename T>
		struct makePointer<T,218>;
		template<typename T>
		struct makePointer<T,219>;
		template<typename T>
		struct makePointer<T,220>;
		template<typename T>
		struct makePointer<T,221>;
		template<typename T>
		struct makePointer<T,222>;
		template<typename T>
		struct makePointer<T,223>;
		template<typename T>
		struct makePointer<T,224>;
		template<typename T>
		struct makePointer<T,225>;
		template<typename T>
		struct makePointer<T,226>;
		template<typename T>
		struct makePointer<T,227>;
		template<typename T>
		struct makePointer<T,228>;
		template<typename T>
		struct makePointer<T,229>;
		template<typename T>
		struct makePointer<T,230>;
		template<typename T>
		struct makePointer<T,231>;
		template<typename T>
		struct makePointer<T,232>;
		template<typename T>
		struct makePointer<T,233>;
		template<typename T>
		struct makePointer<T,234>;
		template<typename T>
		struct makePointer<T,235>;
		template<typename T>
		struct makePointer<T,236>;
		template<typename T>
		struct makePointer<T,237>;
		template<typename T>
		struct makePointer<T,238>;
		template<typename T>
		struct makePointer<T,239>;
		template<typename T>
		struct makePointer<T,240>;
		template<typename T>
		struct makePointer<T,241>;
		template<typename T>
		struct makePointer<T,242>;
		template<typename T>
		struct makePointer<T,243>;
		template<typename T>
		struct makePointer<T,244>;
		template<typename T>
		struct makePointer<T,245>;
		template<typename T>
		struct makePointer<T,246>;
		template<typename T>
		struct makePointer<T,247>;
		template<typename T>
		struct makePointer<T,248>;
		template<typename T>
		struct makePointer<T,249>;
		template<typename T>
		struct makePointer<T,250>;
		template<typename T>
		struct makePointer<T,251>;
		template<typename T>
		struct makePointer<T,252>;
		template<typename T>
		struct makePointer<T,253>;
		template<typename T>
		struct makePointer<T,254>;
		template<typename T>
		struct makePointer<T,255>;
		template<typename T>
		struct makePointer<T,256>;
	};
}
#include "temp_pointers_mP.hpp"
#endif
